export const PersonApi = {
  ranks: [
    {
      id: 0,
      level: 'Cấp bậc',
      querent: 'Querent',
      likes: 'Tim',
      armorial: 'Huy hiệu',
      starCount: 0,
    },
    {
      id: 1,
      level: 'Tập sự',
      querent: '1',
      likes: '1',
      starCount: 1,
    },
    {
      id: 2,
      level: 'Sơ cấp I',
      querent: '50',
      likes: '100',
      starCount: 2,
    },
    {
      id: 3,
      level: 'Sơ cấp II',
      querent: '100',
      likes: '200',
      starCount: 2,
    },
    {
      id: 4,
      level: 'Sơ cấp III',
      querent: '300',
      likes: '500',
      starCount: 2,
    },
    {
      id: 5,
      level: 'Trung cấp I',
      querent: '600',
      likes: '1000',
      starCount: 3,
    },
    {
      id: 6,
      level: 'Trung cấp II',
      querent: '1500',
      likes: '2000',
      starCount: 3,
    },
    {
      id: 7,
      level: 'Trung cấp III',
      querent: '2500',
      likes: '4000',
      starCount: 3,
    },
    {
      id: 8,
      level: 'Cao cấp I',
      querent: '5000',
      likes: '8000',
      starCount: 4,
    },
    {
      id: 9,
      level: 'Cao cấp II',
      querent: '8000',
      likes: '16000',
      starCount: 4,
    },
    {
      id: 10,
      level: 'Cao cấp III',
      querent: '15000',
      likes: '25000',
      starCount: 4,
    },

    {
      id: 11,
      level: 'Siêu cấp',
      querent: '30000',
      likes: '70000',
      starCount: 5,
    },
  ],
};
